/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-07-11 10:09:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%209.0/lib/jstl-1.2.jar", Long.valueOf(1364130896000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%209.0/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<link\n");
      out.write("	href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\"\n");
      out.write("	rel=\"stylesheet\" id=\"bootstrap-css\">\n");
      out.write("<script\n");
      out.write("	src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\n");
      out.write("<script\n");
      out.write("	src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("<!------ Include the above in your HEAD tag ---------->\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\"\n");
      out.write("	integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://use.fontawesome.com/releases/v5.3.1/css/all.css\"\n");
      out.write("	integrity=\"sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("<link href=\"css/login.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<title>Login Form</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div id=\"logreg-forms\">\n");
      out.write("		<form class=\"form-signin\" action=\"login\" method=\"post\">\n");
      out.write("			<h1 class=\"h3 mb-3 font-weight-normal\" style=\"text-align: center\">\n");
      out.write("				Sign in</h1>\n");
      out.write("\n");
      out.write("			<p class=\"text-danger\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMess}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("\n");
      out.write("			<input name=\"user\" type=\"text\" id=\"inputEmail\" class=\"form-control\"\n");
      out.write("				placeholder=\"Username\" required=\"\" autofocus=\"\"> <input\n");
      out.write("				name=\"pass\" type=\"password\" id=\"inputPassword\" class=\"form-control\"\n");
      out.write("				placeholder=\"Password\" required=\"\">\n");
      out.write("\n");
      out.write("			<div class=\"form-group form-check\">\n");
      out.write("				<input name=\"remember\" value=\"1\" type=\"checkbox\"\n");
      out.write("					class=\"form-check-input\" id=\"exampleCheck1\"> <label\n");
      out.write("					class=\"form-check-label\" for=\"exampleCheck1\">Remember me</label>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<button class=\"btn btn-success btn-block\" type=\"submit\">\n");
      out.write("				<i class=\"fas fa-sign-in-alt\"></i> Sign in\n");
      out.write("			</button>\n");
      out.write("			<hr>\n");
      out.write("			<button class=\"btn btn-primary btn-block\" type=\"button\"\n");
      out.write("				id=\"btn-signup\">\n");
      out.write("				<i class=\"fas fa-user-plus\"></i> Sign up New Account\n");
      out.write("			</button>\n");
      out.write("		</form>\n");
      out.write("\n");
      out.write("		<form action=\"signup\" method=\"post\" class=\"form-signup\">\n");
      out.write("			<h1 class=\"h3 mb-3 font-weight-normal\" style=\"text-align: center\">\n");
      out.write("				Sign up</h1>\n");
      out.write("			<input name=\"userName\" type=\"text\" id=\"user-name\"\n");
      out.write("				class=\"form-control\" placeholder=\"Full name...\" required\n");
      out.write("				autofocus=\"\"> \n");
      out.write("			<input name=\"address\" type=\"text\"\n");
      out.write("				id=\"user-name\" class=\"form-control\" placeholder=\"Address...\"\n");
      out.write("				required autofocus=\"\"> \n");
      out.write("			<input name=\"phone\" type=\"text\"\n");
      out.write("				id=\"user-name\" class=\"form-control\" placeholder=\"Your phone...\"\n");
      out.write("				required autofocus=\"\"> \n");
      out.write("			<input name=\"user\" type=\"text\"\n");
      out.write("				id=\"user-name\" class=\"form-control\" placeholder=\"User mail\"\n");
      out.write("				required=\"\" autofocus=\"\"> \n");
      out.write("			<input name=\"pass\" type=\"password\"\n");
      out.write("				id=\"user-pass\" class=\"form-control\" placeholder=\"Password\" required\n");
      out.write("				autofocus=\"\"> \n");
      out.write("			<input name=\"repass\" type=\"password\"\n");
      out.write("				id=\"user-repeatpass\" class=\"form-control\"\n");
      out.write("				placeholder=\"Repeat Password\" required autofocus=\"\">\n");
      out.write("\n");
      out.write("			<button class=\"btn btn-primary btn-block\" type=\"submit\">\n");
      out.write("				<i class=\"fas fa-user-plus\"></i> Sign Up\n");
      out.write("			</button>\n");
      out.write("			<a href=\"#\" id=\"cancel_signup\"><i class=\"fas fa-angle-left\"></i>\n");
      out.write("				Back</a>\n");
      out.write("		</form>\n");
      out.write("		<br>\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("	<script\n");
      out.write("		src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n");
      out.write("	<script\n");
      out.write("		src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"\n");
      out.write("		integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("	<script>\n");
      out.write("            function toggleResetPswd(e) {\n");
      out.write("                e.preventDefault();\n");
      out.write("                $('#logreg-forms .form-signin').toggle() // display:block or none\n");
      out.write("                $('#logreg-forms .form-reset').toggle() // display:block or none\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            function toggleSignUp(e) {\n");
      out.write("                e.preventDefault();\n");
      out.write("                $('#logreg-forms .form-signin').toggle(); // display:block or none\n");
      out.write("                $('#logreg-forms .form-signup').toggle(); // display:block or none\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            $(() => {\n");
      out.write("                // Login Register Form\n");
      out.write("                $('#logreg-forms #forgot_pswd').click(toggleResetPswd);\n");
      out.write("                $('#logreg-forms #cancel_reset').click(toggleResetPswd);\n");
      out.write("                $('#logreg-forms #btn-signup').click(toggleSignUp);\n");
      out.write("                $('#logreg-forms #cancel_signup').click(toggleSignUp);\n");
      out.write("            })\n");
      out.write("        </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
